name: skadi
description: Flutter utilities packages for custom widgets and utilities function.
version: 4.6.0

homepage: https://www.lynical.com
repository: https://github.com/lynical-software/skadi
issue_tracker: https://github.com/lynical-software/skadi/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  universal_platform: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
