name: skadi
<<<<<<< HEAD
description: Flutter utilities packages for custom widgets and utilities function.
version: 0.0.1
=======
description: Flutter utilities packages
version: 0.0.2
>>>>>>> 609a3a01087619ed9ebf9f8b2e5c6a3fea9db35b

homepage: https://www.lynical.com
repository: https://github.com/lynical-software/skadi
issue_tracker: https://github.com/lynical-software/skadi/issues

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  universal_platform: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
